// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/til-crm/ContactDetail.tsx": () => import("../components/mockups/til-crm/ContactDetail.tsx"),
  "./components/mockups/til-crm/Contacts.tsx": () => import("../components/mockups/til-crm/Contacts.tsx"),
  "./components/mockups/til-crm/Dashboard.tsx": () => import("../components/mockups/til-crm/Dashboard.tsx"),
  "./components/mockups/til-crm/Pipeline.tsx": () => import("../components/mockups/til-crm/Pipeline.tsx"),
  "./components/mockups/til-crm/Reports.tsx": () => import("../components/mockups/til-crm/Reports.tsx")
};
