// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/crm-login/CommandCenter.tsx": () => import("../components/mockups/crm-login/CommandCenter.tsx"),
  "./components/mockups/crm-login/Polished.tsx": () => import("../components/mockups/crm-login/Polished.tsx"),
  "./components/mockups/crm-login/Progressive.tsx": () => import("../components/mockups/crm-login/Progressive.tsx"),
  "./components/mockups/crm-login/SplitPanel.tsx": () => import("../components/mockups/crm-login/SplitPanel.tsx"),
  "./components/mockups/crm-login/SplitStory.tsx": () => import("../components/mockups/crm-login/SplitStory.tsx"),
  "./components/mockups/crm-login/ValueFirst.tsx": () => import("../components/mockups/crm-login/ValueFirst.tsx"),
  "./components/mockups/til-crm/ContactDetail.tsx": () => import("../components/mockups/til-crm/ContactDetail.tsx"),
  "./components/mockups/til-crm/Contacts.tsx": () => import("../components/mockups/til-crm/Contacts.tsx"),
  "./components/mockups/til-crm/Dashboard.tsx": () => import("../components/mockups/til-crm/Dashboard.tsx"),
  "./components/mockups/til-crm/Pipeline.tsx": () => import("../components/mockups/til-crm/Pipeline.tsx"),
  "./components/mockups/til-crm/Reports.tsx": () => import("../components/mockups/til-crm/Reports.tsx")
};
